# conda environment description file for moad_tools package testing environment
#
# Creates a conda environment in which the moad_tools package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: moad-tools-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - Click
  - geopandas
  - matplotlib
  - netcdf4
  - pandas
  - pip
  - pytables
  - pyyaml
  - rasterio
  - scipy
  - xarray

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov

  # For documentation links checking
  - sphinx=7.2.6
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=2.0.0

  - pip:
    # For unit tests
    - pytest-randomly

    # editable install of moad_tools package
    - --editable ../
