# conda environment description file for moad_tools package development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f moad_tools/envs/environment-dev.yaml
#   $ conda activate moad-tools
#
# The environment will include all the tools used to develop,
# test, and document the moad_tools package.
#
# See the envs/requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: moad-tools

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - Click<8.0
  - geopandas
  - matplotlib
  - netcdf4
  - pandas
  - pip
  - pytables
  - python=3.10
  - pyyaml
  - rasterio
  - scipy
  - xarray

  # For coding style
  - black

  # For unit tests
  - pytest
  - pytest-cov

  # For documentation
  - sphinx
  - sphinx_rtd_theme
  - sphinx-notfound-page

  - pip:
    # For unit tests
    - pytest-randomly

    # editable install of moad_tools package
    - --editable ../
