# conda environment description file for docs build environment
# on readthedocs.org

name: moad-tools-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
