# conda environment description file for moad_tools package testing environment
#
# Creates a conda environment in which the moad_tools package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: moad-tools-test-no-midoss

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - Click
  - matplotlib
  - netcdf4
  - pandas
  - pip
  - pyyaml
  - scipy
  - xarray

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov

  # For documentation links checking
  - sphinx==8.1.3
  - sphinx-notfound-page==1.0.4
  - sphinx-rtd-theme==3.0.0

  - pip:
    # For unit tests
    - pytest-randomly

    # Install moad_tools package in editable mode
    - --editable ../
