name: sphinx-linkcheck

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  sphinx-linkcheck:
    name: linkcheck docs
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda pkgs
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if envs/environment-test.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('envs/environment-test.yaml') }}

      - uses: goanpeca/setup-miniconda@v1
        with:
           auto-update-conda: true
           auto-activate-base: false
           channel-priority: strict
           environment-file: envs/environment-test.yaml
           use-only-tar-bz2: true # Required for caching to work properly!
           python-version: ${{ matrix.python-version }}
           activate-environment: moad-tools-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: linkcheck docs
        shell: bash -l {0}
        run: |
          (cd docs && make linkcheck)

      - uses: pioug/le-slack-message@v1.0.0
        with:
          ACTION_NAME: ${{ github.repository }} Sphinx linkcheck
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()

      - uses: pioug/le-slack-message@v1.0.0
        with:
          ACTION_NAME: ${{ github.repository }} Sphinx linkcheck
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MIDOSS_WEBHOOK_URL }}
        if: always()
