name: pytest-no-midoss
# Run test suit in an environment that does not include the packages that are needed only
# in the midoss namespace. This tests exceptions and messages to direct user to create
# the appropriate conda environment. Test coverage is not reported from this workflow
# because many tests are skipped.

on:
  push:
    branches: [ '*' ]
  # Enable workflow to be triggered from GitHub CLI, browser, or via API
  # primarily for testing conda env solution for new Python versions
  workflow_dispatch:

jobs:
  pytest-no-midoss:
    permissions:
      contents: read
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        environment: [ 'test-py312-no-midoss', 'test-py313-no-midoss', 'test-py314-no-midoss' ]

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11
        with:
          cache: true
          environments: ${{ matrix.environment }}

      - name: Run pytest
        run: pixi run -e ${{ matrix.environment }} pytest-no-midoss

      # Test coverage is not reported from this workflow because many tests are skipped.
