name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test-coverage:
    name: pytest & coverage report
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda pkgs
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if envs/environment-test.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('envs/environment-test.yaml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
           auto-update-conda: true
           auto-activate-base: false
           channel-priority: strict
           environment-file: envs/environment-test.yaml
           use-only-tar-bz2: true # Required for caching to work properly!
           python-version: ${{ matrix.python-version }}
           activate-environment: moad-tools-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: pytest package with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=$GITHUB_WORKSPACE --cov-report=xml

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Python ${{ matrix.python-version }} pytest & coverage report
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Python ${{ matrix.python-version }} pytest & coverage report
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MIDOSS_WEBHOOK_URL }}
        if: always()

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
        if: always()
